server:
  port: ${serverPort:8080}

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mahechabjj

---

spring:
  profiles: cloud
  data:
    mongodb:
      uri: ${vcap.services.mongo-mahechabjj.credentials.uri}